version: "3"
services:
  database:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=pollair
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - 27017-27019:27017-27019
