import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Footer } from "../../../components/Footer";

import pageStyles from "../../../styles/Page.module.scss";

const Answer: NextPage = () => {
  return (
    <div className={pageStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={pageStyles.main}>Answering</main>

      <Footer />
    </div>
  );
};

export default Answer;
