import { Button } from "@chakra-ui/button";
import { Input } from "@chakra-ui/input";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import ChoicesInput from "../components/ChoicesInput";
import { Footer } from "../components/Footer";
import styles from "../styles/Home.module.scss";

import pageStyles from "../styles/Page.module.scss";
import { createPoll } from "../utils/poll";

const Home: NextPage = () => {
  const [name, setName] = useState("");
  const [choices, setChoices] = useState<string[]>([]);

  const handleCreate = async () => {
    const res = await createPoll({ name, choices });
    console.log(res);
  };

  return (
    <div className={pageStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={pageStyles.main}>
        <Image src="/logo.png" width={200} height={200} alt="" />
        <h2 className={styles.title}>Question...</h2>
        <Input
          className={styles.name}
          value={name}
          onChange={(e) => setName(e.target.value)}
          size="sm"
          variant="filled"
          bg="brand.lighter"
          _hover={{ bg: "brand.base" }}
        />
        <h2 className={styles.title}>Choix...</h2>
        <ChoicesInput onChange={setChoices} />
        <Button
          size="sm"
          className={styles.createButton}
          bg="brand.base"
          _hover={{ bg: "brand.darker", color: "brand.lighter" }}
          onClick={handleCreate}
        >
          Créer le sondage
        </Button>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
